# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15a626908877ccc645e24c61ad2bb099b8974ebd28719a2a3773e77b0c2abf272721929f0b7e94c966ba9d700a7c8b9f08cd207141558adc632685f77ec8cb0f

test:
  secret_key_base: 5dc01ae1eb2f41d387a59371b03f216413723c825761dd6ed8d86d1c628d13baa6b343e873b9ef5ebb97f78fbead5a9f232f94240204dc2a095421d8521e4c51

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
